version: "3"
services:
  frontend:
    image: ssofok02/hotel_app_frontend_single_node_memdb
    entrypoint: frontend
    ports:
      - "8080:8080"
    restart: always

  profile:
    image: ssofok02/hotel_app_profile_single_node_memdb
    entrypoint: profile
    ports:
      - "8081:8081"
    restart: always
 
  search:
    image: ssofok02/hotel_app_search_single_node_memdb
    entrypoint: search
    ports:
      - "8082:8082"
    restart: always

  geo:
    image: ssofok02/hotel_app_geo_single_node_memdb
    entrypoint: geo
    ports:
      - "8083:8083"
    restart: always

  rate:
    build:
      context: .
      args:
        - DB=mongodb
    image: hotel_app_rate_single_node_mongodb
    entrypoint: rate
    ports:
      - "8084:8084"
    depends_on:
      - mongodbrate
    restart: always

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: 'hotel_app_jaeger'
    ports:
      - "14269"
      - "5778:5778"
      - "14268:14268"
      - "14267"
      - "16686:16686"
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
    restart: always
  
  mongodbrate:
    image: mongo
    container_name: 'hotel_app_rate_mongo'
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - rate:/data/db

volumes:
  rate:  
